# Generated by Django 2.1.7 on 2019-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nmcliente', models.CharField(max_length=100)),
                ('dtnascimento', models.DateTimeField()),
                ('dtcoleta', models.DateTimeField()),
                ('dtentrega', models.DateTimeField()),
                ('nmmedico', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
